### ISSUE TITLE
Program Doesnt Make Webhook Sends Messages

### ISSUE THREAD

**Issue by CBHELEC** [AKGaming0001/pokemon-coords#13]
Ive done everything correct and the test messages show up - but when i start the bot and leave it runing for 5+ minutes nothing gets sent

**Comment by AKGaming0001** [comment]
Backend server ain't running, i'm out of funds ;-;

**Comment by AKGaming0001** [comment]
> Ive done everything correct and the test messages show up - but when i start the bot and leave it runing for 5+ minutes nothing gets sent

Server is back up try again :)
