### ISSUE TITLE
Bot doesn't respond down frequently 

### ISSUE THREAD

**Issue by ManavGhiya001** [AKGaming0001/pokemon-coords#2]
Kindly fix the issue that bot goes down frequently 
![Screenshot_20220325-100126_Discord](https://user-images.githubusercontent.com/102342631/160054635-5edcd989-6d19-4e8d-979e-ecb3dc5891d6.jpg)

**Comment by AKGaming0001** [comment]
i'll fix that soon, it's probably due to command spams or two people using same command at the same time
