### ISSUE TITLE
Cooldown must be lowered

### ISSUE THREAD

**Issue by ManavGhiya** [AKGaming0001/pokemon-coords#5]
My server has purchased premium ` https://discord.gg/URnVHUdh9H  ` so cooldown must be reduced to 2s only
![Screenshot_20220508-101736](https://user-images.githubusercontent.com/79264298/167282917-74688727-fca0-45db-9afa-c363e17e2cf4.jpg)

**Comment by AKGaming0001** [comment]
alright ill fix it after the pokelist 30sec cd as it breaks the bot
