### ISSUE TITLE
Please fix asap and make sure this doesn't happen again

### ISSUE THREAD

**Issue by ManavGhiya** [AKGaming0001/pokemon-coords#6]
Please fix asap and make sure this doesn't happen again
![Screenshot_20220516-124414](https://user-images.githubusercontent.com/79264298/168539209-1ba3af95-2f06-4720-b1e2-dddc638f7a38.jpg)

**Comment by AKGaming0001** [comment]
it happens when 3 people use command after the $pokelist command, the bot takes 30secs to process the pokelist and if someone uses other command in those 30secs twice,  the bot breaks smh.

**Comment by ManavGhiya** [comment]
> it happens when 3 people use command after the $pokelist command, the bot takes 30secs to process the pokelist and if someone uses other command in those 30secs twice, the bot breaks smh.

Could you please disable pokelist then ?
It will be fine if there is no pokelist but the pokesearch has to function properly without breaking
